export interface IconCategory {
  key: string;
  label: string;
  keywords: string[];
}

// 순서가 우선순위입니다. 아이콘 이름(소문자, 하이픈 제거)에 키워드가 포함되면
// 그 카테고리로 분류하고, 어떤 키워드에도 걸리지 않으면 마지막 "기타"로 빠집니다.
export const ICON_CATEGORIES: IconCategory[] = [
  {
    key: "arrows",
    label: "화살표 & 방향전환",
    keywords: [
      "arrow",
      "chevron",
      "corner",
      "move",
      "expand",
      "shrink",
      "maximize",
      "minimize",
      "redo",
      "undo",
      "rotate",
      "refresh",
      "repeat",
      "shuffle",
      "unfold",
      "fold",
    ],
  },
  {
    key: "user-account",
    label: "사용자 & 계정",
    keywords: [
      "user",
      "person",
      "contact",
      "idcard",
      "fingerprint",
      "baby",
      "accessibility",
      "graduationcap",
    ],
  },
  {
    key: "files-docs",
    label: "파일 & 문서",
    keywords: [
      "file",
      "folder",
      "archive",
      "clipboard",
      "paperclip",
      "book",
      "notebook",
      "newspaper",
      "scroll",
      "stickynote",
      "bookmark",
      "library",
    ],
  },
  {
    key: "communication",
    label: "통신 & 메시지",
    keywords: [
      "mail",
      "message",
      "phone",
      "voicemail",
      "rss",
      "podcast",
      "send",
      "atsign",
      "megaphone",
      "chat",
      "inbox",
      "forward",
      "reply",
    ],
  },
  {
    key: "media",
    label: "미디어 & 재생",
    keywords: [
      "play",
      "pause",
      "music",
      "video",
      "film",
      "camera",
      "mic",
      "speaker",
      "volume",
      "headphone",
      "radio",
      "cast",
      "clapperboard",
      "disc",
      "tv",
      "webcam",
      "aperture",
      "image",
      "gallery",
    ],
  },
  {
    key: "text-edit",
    label: "텍스트 & 편집",
    keywords: [
      "text",
      "bold",
      "italic",
      "underline",
      "align",
      "list",
      "type",
      "edit",
      "pen",
      "pencil",
      "highlighter",
      "eraser",
      "quote",
      "heading",
      "spellcheck",
      "indent",
      "case",
      "strikethrough",
      "subscript",
      "superscript",
    ],
  },
  {
    key: "dev-code",
    label: "개발 & 코드",
    keywords: [
      "code",
      "terminal",
      "braces",
      "brackets",
      "binary",
      "bug",
      "webhook",
      "regex",
      "git",
      "variable",
      "function",
      "parentheses",
      "ligature",
      "component",
      "command",
    ],
  },
  {
    key: "layout-ui",
    label: "레이아웃 & UI",
    keywords: [
      "panel",
      "layout",
      "sidebar",
      "frame",
      "dock",
      "columns",
      "rows",
      "grip",
      "fullscreen",
      "form",
      "appwindow",
    ],
  },
  {
    key: "tools-settings",
    label: "도구 & 설정",
    keywords: [
      "wrench",
      "hammer",
      "screwdriver",
      "settings",
      "sliders",
      "drill",
      "ruler",
      "scale",
      "magnet",
      "gavel",
      "pickaxe",
      "anvil",
      "forklift",
      "factory",
      "nut",
      "cog",
      "construction",
    ],
  },
  {
    key: "home-furniture",
    label: "집 & 가구",
    keywords: [
      "house",
      "home",
      "bed",
      "bath",
      "sofa",
      "chair",
      "armchair",
      "lamp",
      "door",
      "window",
      "fence",
      "hotel",
      "garage",
      "stairs",
      "blinds",
      "curtain",
    ],
  },
  {
    key: "commerce",
    label: "쇼핑 & 결제",
    keywords: [
      "shopping",
      "cart",
      "creditcard",
      "wallet",
      "dollar",
      "euro",
      "pound",
      "yen",
      "coins",
      "receipt",
      "tag",
      "gift",
      "store",
      "bitcoin",
      "banknote",
      "piggybank",
      "handshake",
      "package",
      "truck",
      "warehouse",
      "percent",
    ],
  },
  {
    key: "devices",
    label: "기기 & 하드웨어",
    keywords: [
      "laptop",
      "monitor",
      "tablet",
      "smartphone",
      "printer",
      "keyboard",
      "mouse",
      "harddrive",
      "server",
      "cpu",
      "battery",
      "usb",
      "router",
      "bluetooth",
      "wifi",
      "signal",
      "chip",
      "memorystick",
      "plug",
      "power",
      "gamepad",
      "joystick",
      "watch",
      "projector",
    ],
  },
  {
    key: "weather-nature",
    label: "날씨 & 자연",
    keywords: [
      "cloud",
      "sun",
      "moon",
      "rain",
      "snow",
      "wind",
      "umbrella",
      "thermometer",
      "tree",
      "leaf",
      "flower",
      "mountain",
      "wave",
      "droplet",
      "flame",
      "sunrise",
      "sunset",
      "sprout",
      "rainbow",
      "tornado",
      "volcano",
      "earth",
      "sparkle",
    ],
  },
  {
    key: "map-location",
    label: "지도 & 이동수단",
    keywords: [
      "map",
      "pin",
      "navigation",
      "compass",
      "globe",
      "flag",
      "route",
      "car",
      "bus",
      "train",
      "plane",
      "ship",
      "bike",
      "sailboat",
      "anchor",
      "rocket",
      "fuel",
      "traffic",
      "tram",
      "milestone",
      "signpost",
      "parking",
    ],
  },
  {
    key: "time-schedule",
    label: "시간 & 일정",
    keywords: ["calendar", "clock", "timer", "history", "alarm", "hourglass"],
  },
  {
    key: "chart-data",
    label: "차트 & 데이터",
    keywords: [
      "chart",
      "trending",
      "activity",
      "database",
      "table",
      "grid",
      "gauge",
      "funnel",
      "network",
      "workflow",
      "layers",
      "boxes",
      "sigma",
    ],
  },
  {
    key: "status-security",
    label: "상태 & 보안",
    keywords: [
      "check",
      "alert",
      "info",
      "bell",
      "shield",
      "lock",
      "unlock",
      "eye",
      "key",
      "ban",
      "octagon",
      "siren",
      "warning",
    ],
  },
  {
    key: "health",
    label: "건강 & 의료",
    keywords: [
      "heart",
      "pill",
      "syringe",
      "stethoscope",
      "hospital",
      "bandage",
      "brain",
      "cross",
      "dna",
      "microscope",
      "tooth",
      "bone",
      "ear",
      "pulse",
    ],
  },
  {
    key: "food-drink",
    label: "음식 & 음료",
    keywords: [
      "coffee",
      "cup",
      "pizza",
      "cake",
      "apple",
      "egg",
      "fish",
      "beef",
      "wine",
      "beer",
      "icecream",
      "utensils",
      "sandwich",
      "salad",
      "soup",
      "cookie",
      "candy",
      "carrot",
      "banana",
      "cherry",
      "grape",
      "citrus",
      "milk",
      "popcorn",
      "croissant",
      "donut",
      "drumstick",
      "vegan",
      "wheat",
    ],
  },
  {
    key: "animals",
    label: "동물",
    keywords: [
      "cat",
      "dog",
      "bird",
      "bug",
      "rabbit",
      "turtle",
      "squirrel",
      "paw",
      "bee",
      "shell",
      "snail",
      "worm",
      "rat",
      "shrimp",
      "feather",
    ],
  },
  {
    key: "sports-hobby",
    label: "스포츠 & 취미",
    keywords: [
      "dumbbell",
      "trophy",
      "medal",
      "puzzle",
      "dice",
      "target",
      "volleyball",
      "football",
      "swords",
      "sword",
      "gem",
      "palette",
      "brush",
      "guitar",
      "piano",
      "drum",
      "party",
      "ticket",
      "kite",
      "tent",
    ],
  },
  {
    key: "shapes-symbols",
    label: "도형 & 기호",
    keywords: [
      "square",
      "circle",
      "triangle",
      "hexagon",
      "pentagon",
      "octagon",
      "star",
      "shapes",
      "diamond",
      "spline",
      "vector",
      "asterisk",
      "infinity",
    ],
  },
  {
    key: "etc",
    label: "기타",
    keywords: [],
  },
];

// PascalCase 아이콘 이름을 단어 단위로 쪼갭니다 (예: "LocateFixed" -> ["locate", "fixed"]).
function splitWords(name: string): string[] {
  const words = name.match(/[A-Z][a-z0-9]*/g);
  return (words ?? [name]).map((word) => word.toLowerCase());
}

// 단어 경계를 넘지 않는 1~3개 연속 단어 조합만 생성해, "search"가 "ear"를
// 포함한다는 이유만으로 매칭되는 것 같은 오탐을 막습니다.
function wordCombinations(words: string[], maxSpan = 3): Set<string> {
  const combos = new Set<string>();
  for (let start = 0; start < words.length; start++) {
    let combo = "";
    for (let span = 0; span < maxSpan && start + span < words.length; span++) {
      combo += words[start + span];
      combos.add(combo);
    }
  }
  return combos;
}

export function categorizeIconName(name: string): string {
  const combos = wordCombinations(splitWords(name));
  for (const category of ICON_CATEGORIES) {
    if (category.keywords.some((keyword) => combos.has(keyword))) {
      return category.key;
    }
  }
  return "etc";
}
